### ISSUE TITLE
I cant start the website

### ISSUE THREAD

**Issue by nykroy** [AnderUR/Employee-Scheduling-System#1]
Multiple tables with uppercase that on sql file ar in lowercase. For example scheduledshifts in code is ScheduledShifts

In other hands manageEmployee show like that 

![image](https://user-images.githubusercontent.com/7745881/124606017-c6ea2500-de6c-11eb-861a-a9cc361375aa.png)

What i am doing wrong?  (URL /LibServices/index.php/timesheet/manageEmployee)

**Comment by AnderUR** [comment]
Sorry for the late response. Hopefully, you have resolved the problem. If not, the path for the CSS and JS are incorrect in your installation.  Please take a look at the header.php and footer.php and change the path for those files accordingly. If your server is localhost and your CodeIgniter installation is named Libservices, it works (I tested again as to not misinform you).
